# Generated by Django 5.0.6 on 2024-08-14 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
