# Generated by Django 5.0.6 on 2024-07-03 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exhibition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('curator', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('brief_description', models.CharField(max_length=300)),
                ('thumbnail', models.ImageField(upload_to='exhibitions/thumbnails/')),
            ],
        ),
    ]
