# Generated by Django 5.0.6 on 2024-06-20 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('medium', models.CharField(choices=[('painting', 'Painting'), ('sculpture', 'Sculpture'), ('photography', 'Photography')], max_length=100)),
                ('year_created', models.DateField()),
                ('image', models.ImageField(null=True, upload_to='static/img/')),
                ('description', models.TextField(max_length=2000)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
