# Generated by Django 5.0.6 on 2024-06-24 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artworks', '0004_alter_artwork_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='genre',
            field=models.CharField(choices=[('abstract', 'Abstract'), ('landscape', 'Landscape'), ('portrait', 'Portrait'), ('still_life', 'Still Life'), ('conceptual', 'Conceptual'), ('figurative', 'Figurative')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='artwork',
            name='price_range_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='artwork',
            name='price_range_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='artwork',
            name='style',
            field=models.CharField(blank=True, choices=[('modern', 'Modern'), ('contemporary', 'Contemporary'), ('impressionism', 'Impressionism'), ('expressionism', 'Expressionism'), ('realism', 'Realism'), ('surrealism', 'Surrealism')], max_length=100, null=True),
        ),
    ]
