# Generated by Django 5.0.6 on 2024-06-24 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artworks', '0005_artwork_genre_artwork_price_range_max_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='genre',
            field=models.CharField(choices=[('landscape', 'Landscape'), ('portrait', 'Portrait'), ('conceptual', 'Conceptual'), ('figurative', 'Figurative')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='style',
            field=models.CharField(blank=True, choices=[('modern', 'Modern'), ('expressionism', 'Expressionism'), ('realism', 'Realism')], max_length=100, null=True),
        ),
    ]
