# Generated by Django 5.0.6 on 2024-07-08 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artworks', '0014_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='genre',
            field=models.CharField(blank=True, choices=[('landscape', 'Landscape'), ('portrait', 'Portrait'), ('conceptual', 'Conceptual'), ('figurative', 'Figurative'), ('street', 'Street'), ('documentary', 'Documentary')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='medium',
            field=models.CharField(blank=True, choices=[('painting', 'Painting'), ('sculpture', 'Sculpture'), ('photography_digital', 'Digital Photography'), ('photography_film', 'Film Photography'), ('digital_painting', 'Digital Painting'), ('3d_modeling', '3D Modeling'), ('vr_art', 'Virtual Reality Art'), ('ar_art', 'Augmented Reality Art'), ('digital_collage', 'Digital Collage'), ('generative_art', 'Generative Art')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='style',
            field=models.CharField(blank=True, choices=[('modern', 'Modern'), ('expressionism', 'Expressionism'), ('realism', 'Realism'), ('abstract', 'Abstract')], max_length=100, null=True),
        ),
    ]
