# Generated by Django 5.0.6 on 2024-09-07 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artworks', '0015_alter_artwork_genre_alter_artwork_medium_and_more'),
        ('Authentication', '0009_remove_artist_contact_email_alter_artist_biography_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='artist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arts', to='Authentication.artist'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='description',
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
