# Generated by Django 5.0.6 on 2024-09-07 19:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artworks', '0017_alter_artwork_artist_alter_artwork_year_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exhibition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('artworks', models.ManyToManyField(blank=True, related_name='exhibitions', to='Artworks.artwork')),
            ],
        ),
    ]
