# Generated by Django 5.0.6 on 2024-07-06 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0004_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='category',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
