# Generated by Django 5.0.6 on 2024-07-06 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0005_artist_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='social_links',
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'Twitter'), ('instagram', 'Instagram')], max_length=50)),
                ('url', models.URLField()),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='Authentication.artist')),
            ],
        ),
    ]
