# Generated by Django 5.0.6 on 2024-07-06 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0006_remove_artist_social_links_sociallink'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='social_links',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='SocialLink',
        ),
    ]
