# Generated by Django 5.0.6 on 2024-07-04 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_wishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
