# Generated by Django 5.0.6 on 2024-07-27 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_ordereditem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordereditem',
            old_name='product',
            new_name='artwork',
        ),
        migrations.RemoveField(
            model_name='ordereditem',
            name='address',
        ),
        migrations.RemoveField(
            model_name='ordereditem',
            name='mobile',
        ),
    ]
