# Generated by Django 5.0.6 on 2024-07-28 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_rename_product_ordereditem_artwork_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordereditem',
            name='transaction_uuid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
