# Generated by Django 5.0.6 on 2024-07-02 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Artists', '0003_alter_artist_user'),
        ('Artworks', '0013_alter_artwork_artist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Artist',
        ),
    ]
