# Generated by Django 5.0.6 on 2024-07-04 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_wishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
