# Generated by Django 5.0.6 on 2024-07-05 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_delete_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='occupation',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
