# Generated by Django 5.0.6 on 2024-07-06 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_alter_visitor_biography'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='contact_email',
        ),
    ]
