# Generated by Django 5.0.6 on 2024-07-17 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_remove_visitor_contact_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True),
        ),
    ]
