# Generated by Django 5.0.6 on 2024-07-27 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0009_visitor_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='nearest_landmark',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='ward',
            field=models.IntegerField(null=True),
        ),
    ]
